### ISSUE TITLE
ieftool skips policies during deployment

### ISSUE THREAD

**Issue by gazzyt** [judedaryl/go-ieftool#1]
First, thanks for making this project - it really is essential for us doing devops with B2C custom policies.

Today I ran into an issue where a new policy I had created was not being deployed by ieftool and for once it wasn't just a bad policy file.

I started stepping through your code in the debugger and traced the problem to this function:

```
func findChildPolicies(policies *[]Policy, policyId string) []Policy {
	_policies := []Policy{}
	for i, policy := range *policies {
		if policy.ParentPolicyId == policyId {
			_policies = append(_policies, policy)
			*policies = remove(*policies, i)
		}
	}
	return _policies
}
```

I can't share my policy files but a hypothetical will show the issue.

Let's say we are calling this function to find child policies of PolicyA and we have the following `policies`:
PolicyB with parent PolicyA
PolicyC with parent PolicyA
PolicyD with parent PolicyC

On the first pass through the for loop we have i = 0 and policy = PolicyB. The parent matches so the call to `remove` executes and leaves us the following remaining policies:
PolicyC with parent PolicyA
PolicyD with parent PolicyC

On the second pass through the for loop we have i = 1 and policy = PolicyC. The parent matches so the call to `remove` executes but this time it removes the policy at index 1 which is not PolicyC. It removes PolicyD instead and thus PolicyD will not be deployed.

My simple fix was to just not call `remove` from this function - it doesn't seem to necessary at this point in the execution and certainly fixed my issue.

I'll send a PR with my changes.

**Comment by judedaryl** [comment]
i vaguely remember why i added the remove there but i think it was to save time for the next loop. but i think its a negligible performance hit as most people working on B2C are really just working on < 20 policies. I worked on a project with 100 policies but that's rare and even then performance would still be negligible. 

thank you for raising this issue and sending out a PR! Once this is merged, i'll add a new release, just rerun your script or rerun install.sh as it downloads the latest version.

**Comment by gazzyt** [comment]
Thanks for merging. Your new 1.0.7 release is working great so we can close this issue now.
